config_file: configs/weather.yaml
data:
  data_path: ./data/
  features: 21
  seq_len: 96
datasets:
- weather
hardware:
  num_gpus: 8
lambda_search:
  default: 0.01
  values:
  - 0.01
  - 0.1
  - 1.0
  - 2.0
  - 5.0
  - 10.0
  - 50.0
  - 100.0
logging:
  save_frequency: 10
  verbose: true
model:
  d_model: 128
  d_state: 16
  decoder_hidden_dim: 64
  decoder_layers: 2
  dt_rank: auto
  expand_factor: 2
  n_layers: 4
prediction_lengths:
- 96
- 192
- 336
- 720
robustness:
  impulse_noise:
    magnitude_factor: 5.0
    probability: 0.05
  spurious_correlation:
    amplitude_factor: 0.5
    correlation_strength: 0.7
    frequency: 0.1
training:
  batch_size: 32
  learning_rate: 0.001
  max_epochs: 100
  patience: 3
  seed: 43
