config_file: configs/all_datasets_config.yaml
data:
  data_path: ./data/
  seq_len: 96
datasets:
- ETTh1
- ETTh2
- ETTm1
- ETTm2
- weather
- traffic
hardware:
  num_gpus: 8
lambda_search:
  default: 0.01
  values:
  - 0.001
  - 0.005
  - 0.01
  - 0.05
  - 0.1
  - 0.5
  - 1.0
logging:
  save_frequency: 10
  verbose: true
model:
  d_model: 128
  d_state: 16
  decoder_hidden_dim: 64
  decoder_layers: 2
  dt_rank: auto
  expand_factor: 2
  n_layers: 4
model_overrides:
  traffic:
    d_model: 256
    d_state: 32
    decoder_hidden_dim: 128
prediction_lengths:
- 96
- 192
- 336
- 720
robustness:
  impulse_noise:
    magnitude_factor: 5.0
    probability: 0.05
  spurious_correlation:
    amplitude_factor: 0.5
    correlation_strength: 0.7
    frequency: 0.1
training:
  batch_size: 32
  learning_rate: 0.001
  max_epochs: 100
  patience: 3
  seed: 2024
training_overrides:
  traffic:
    batch_size: 16
