# MPS-SSM Configuration for ETT Datasets

# Datasets to evaluate
datasets:
  - ETTh1
  - ETTh2
  - ETTm1
  - ETTm2

# Prediction lengths to test
prediction_lengths:
  - 96
  - 192
  - 336
  - 720

# Data configuration
data:
  data_path: "data"  # Path to the directory containing ETT CSV files
  seq_len: 96       # Input sequence length
  features: 7       # Number of features in ETT datasets
  target_col: 6     # Target column index (OT column is the 7th column, 0-indexed)

# Model configuration
model:
  d_model: 256
  n_layers: 4
  d_state: 16
  expand_factor: 2
  dt_rank: "auto"
  decoder_hidden_dim: 128
  decoder_layers: 2
  dropout: 0.1

# Training configuration
training:
  batch_size: 32
  learning_rate: 0.001
  max_epochs: 100
  patience: 3       # Early stopping patience
  seed: 42

# Lambda search configuration
lambda_search:
  values: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0]  # Lambda values to search
  default: 0.01  # Default lambda if search fails

# Hardware configuration
hardware:
  num_gpus: 8  # Number of available GPUs